# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Simmer
description: A Web platform for science in action.
author:
  name: Oliver Lade
  email: oliver@runsimmer.com

include: ['.htaccess']

source: app
destination: dist

# _config.build.yml sets future and show_drafts to false on `grunt build`
# Uncomment when this can work with vanilla Jekyll as well.
#future: true
#show_drafts: true
excerpt_separator: <!--more-->
permalink: pretty

sass:
  sass_dir: _scss

# Markdown library: no explicit preference, yet.
# markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments
